version: '3.9'

services:
  db:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - forecast-backend:/var/lib/postgresql/data
    restart: always

volumes:
  forecast-backend: